### ISSUE TITLE
如何确定storeblock地址？

### ISSUE THREAD

**Issue by JsHuang** [skysider/VulnPOC#1]
从exp.py来看，是不断尝试地址，只要覆盖ACL字符串成功，就说明找到了storeblock了？
没有可能写到其他的合法storeblock么？

**Comment by skysider** [comment]
包含acl的storeblock是storeblock链表里地址最靠前的，爆破顺序是从低地址到高地址，所以第一个符合要求的（低12bit固定是0x480且是一个正常的storeblock）应该就是了

**Comment by JsHuang** [comment]
那低比特0x480是如何确定的呢?

**Comment by skysider** [comment]
这个就是根据exim实际运行的时候调试得知的，虽然有ASLR，但是低12bit是固定的
